---
title: "MUSA500 - HW1"
author: "Chenxi Zhu, Teresa Chang, and Tiffany Luo "
date: "Octobor 1,2023"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---
## 1. Introduction
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, warning = FALSE}
options(scipen=10000000)

library(tidyverse)
library(kableExtra)
library(caret)
library(knitr) 
library(pscl)
library(plotROC)
library(pROC)
library(lubridate)
library(scales)
library(stargazer)
library(cowplot)


```

## 2. Methods
### 2.1 Data Cleaning
### 2.2 Exploratory Data Analysis
### 2.3 Multiple Regression Analysis
### 2.4 Additional Analyses
### 2.5 Software

## 3. Results
### 3.1 Exploratory Results   
### 3.2 Regression Results
### 3.3 Regression Assumption Checks
### 3.4 Additional Models
```{r}
data <- read.csv("/Users/teresachang/Downloads/RegressionData.csv")
```

```{r}
MedHouseValue = c('Median House Value', mean(data$MEDHVAL), sd(data$MEDHVAL))
HH_poverty = c('# Households Living in Poverty', mean(data$NBELPOV100), sd(data$NBELPOV100))
bachelor = c('% of Individuals with Bachelor’s Degrees or Higher', mean(data$PCTBACHMOR), sd(data$PCTBACHMOR))
vacant = c('% of Vacant Houses', mean(data$PCTVACANT), sd(data$PCTVACANT))
SingleHouse = c('% of Single House Units', mean(data$PCTSINGLES), sd(data$PCTSINGLES))

table = as.data.frame(t(data.frame(
              MedHouseValue,
              HH_poverty,
              bachelor,
              vacant,
              SingleHouse
              )))

colnames(table) = c("Variable", "Mean", "SD")

table
```

```{r}
MedHV = ggplot(data) +
        geom_histogram(aes(MEDHVAL))
HHpov = ggplot(data) +
        geom_histogram(aes(NBELPOV100))
bach = ggplot(data) +
        geom_histogram(aes(PCTBACHMOR))
vacant = ggplot(data) +
        geom_histogram(aes(PCTVACANT))
SingleH = ggplot(data) +
        geom_histogram(aes(PCTVACANT))

MedHV
HHpov
bach
vacant
SingleH

```

```{r}


```


## 4. Discussion and Limitations